name: myproject_functions
description: My project functions
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  firebase_functions_interop: ^1.0.0-dev
  firebase_admin_interop: ^1.0.0-dev
  node_io: ^1.0.0-dev
  node_http: ^1.0.0-dev
  collection: ^1.14.10
  front_end: ^0.1.2
  path: ^1.6.1

dev_dependencies:
  build_runner: ^0.9.0
  build_node_compilers: ^0.1.0

